### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Jhonatan-Souza** [Shobhit20/Image-Captioning#11]
Colocations handled automatically by placer.
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    text(image)
  File "test.py", line 11, in text
    sd = SceneDesc.scenedesc()
  File "C:\Users\jhona\Desktop\Image-Captioning-master\SceneDesc.py", line 17, in __init__
    self.image_encodings = pickle.load( open( "image_encodings.p", "rb",  ) )
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 32: ordinal not in range(128)

**Comment by avideep** [comment]
You have to specify the encoding format while loading. Replace line 17 of "C:\Users\jhona\Desktop\Image-Captioning-master\SceneDesc.py" with the following line :

self.image_encodings = pickle.load( open( "image_encodings.p", "rb" ),encoding='latin1' )
